import Head from "next/head";
import { useEffect } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Footer from "@/Components/Dashboard/Footer";
import Navbar from "@/Components/Dashboard/Navbar";
import DashContent from "@/Components/Dashboard/DashContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Elly | AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`dashboardContainer ${inter.className}`}>
        <Navbar />
        <Footer />
        <DashContent />
      </main>
    </>
  );
}
